name: Fly.io Deployment

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        run: |
          flyctl auth docker
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
